"""create canvases table

Revision ID: db8640412864
Revises: 0005
Create Date: 2026-06-18 09:35:11.610427
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db8640412864'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False, comment='Serialized canvas state: { nodes: [...], edges: [...], viewport: {...} }'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvases_user_id'), 'canvases', ['user_id'], unique=False)
    op.drop_index(op.f('ix_novels_created_at'), table_name='novels')
    op.drop_index(op.f('ix_novels_embedding_ivfflat'), table_name='novels', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('tasks', 'workflow_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Type of workflow: generate_novel, generate_lyrics, generate_song, generate_video',
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='PENDING | RUNNING | SUCCESS | FAILED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('tasks', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Progress percentage 0.0–100.0',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('tasks', 'current_step',
               existing_type=sa.VARCHAR(length=100),
               comment='Name of the currently executing step',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('tasks', 'input_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Original input parameters passed when creating the workflow',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('tasks', 'checkpoint_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Intermediate data for checkpoint / resume support',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('tasks', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Final output of the workflow',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id_created_at'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_user_id_created_at'), 'tasks', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_status_created_at'), 'tasks', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.alter_column('tasks', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Final output of the workflow',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('tasks', 'checkpoint_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Intermediate data for checkpoint / resume support',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('tasks', 'input_params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Original input parameters passed when creating the workflow',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('tasks', 'current_step',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Name of the currently executing step',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('tasks', 'progress',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Progress percentage 0.0–100.0',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='PENDING | RUNNING | SUCCESS | FAILED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('tasks', 'workflow_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Type of workflow: generate_novel, generate_lyrics, generate_song, generate_video',
               existing_nullable=False)
    op.create_index(op.f('ix_novels_embedding_ivfflat'), 'novels', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_novels_created_at'), 'novels', ['created_at'], unique=False)
    op.drop_index(op.f('ix_canvases_user_id'), table_name='canvases')
    op.drop_table('canvases')
    # ### end Alembic commands ###
