name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 103.233.253.246
          username: root
          password: xtgbKJUD0671
          script: |
            cd /root/Story2Video
            git pull
            docker compose restart app
